version: '3.8'
services:
  auto-ocr-pj:
    build:
      context: .
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    container_name: auto-ocr-pj
    volumes:
      - ./app-auto-ocr/data:/home/auto-ocr/.local/share/auto-ocr
      - ./app-auto-ocr/config:/home/auto-ocr/.config/auto-ocr
      - ${AUTO_OCR_SOURCE_AND_DESTINATION}:/auto-ocr-data
      - "/etc/localtime:/etc/localtime:ro"
    command: ["auto-ocr", "-plf"]
